-- schema.sql
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST;

CREATE TABLE POST (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT
);

CREATE TABLE COMMENT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    post_id BIGINT NOT NULL,
    writer VARCHAR(100),
    content TEXT,
    FOREIGN KEY (post_id) REFERENCES POST(id) ON DELETE CASCADE
);