CREATE DEFINER=`juanpark`@`%` PROCEDURE `PRO12_CURSOR_SELECT01`()
BEGIN
-- 사원의 이름과 봉급을 출력 해보자.
  DECLARE done INT DEFAULT FALSE;
  DECLARE RES_ENAME VARCHAR (20);
  DECLARE RES_SAL DECIMAL(10,2);
  DECLARE cur1 CURSOR FOR SELECT ENAME, SAL FROM emp_test;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

  OPEN cur1;
  read_loop: LOOP
    FETCH cur1 INTO RES_ENAME, RES_SAL;
    IF done THEN
        LEAVE read_loop;
    END IF;
    SELECT RES_ENAME AS 이름, RES_SAL AS 급여;
   END LOOP;
   CLOSE cur1;
END