CREATE DEFINER=`juanpark`@`%` PROCEDURE `PRO12_CURSOR_SELECT`()
BEGIN
-- 사원의 이름과 봉급을 출력 해보자.
	DECLARE done INT DEFAULT FALSE;
	DECLARE RES_ENAME VARCHAR(30);
	DECLARE RES_SAL DECIMAL(6,2); 
	
    DECLARE cur1 CURSOR FOR SELECT ENAME, SAL FROM EMP_TEST;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

	OPEN cur1;

	read_loop: LOOP
		FETCH cur1 INTO RES_ENAME, RES_SAL;
    
		IF done THEN
		  LEAVE read_loop;
		END IF;
	
		SELECT ENAME, SAL;
	END LOOP;
	CLOSE cur1;
END