CREATE DEFINER=`juanpark`@`%` FUNCTION `FUN04`(D_DEPTNO INT) RETURNS varchar(100) CHARSET utf8mb4
    READS SQL DATA
BEGIN
    DECLARE D_NAME VARCHAR(100);
    SELECT DNAME INTO D_NAME FROM  DEPT WHERE DEPTNO =D_DEPTNO;
    RETURN D_NAME;
END