CREATE DEFINER=`juanpark`@`%` PROCEDURE `PRO12_CURSOR_SELECT02`()
BEGIN
-- 사원의 이름과 봉급을 출력 해보자.
	DECLARE done INT DEFAULT FALSE;
	DECLARE RES_ENAME VARCHAR(30);
	DECLARE RES_SAL DECIMAL(10,2); 

    DECLARE cur1 CURSOR FOR SELECT ENAME, SAL FROM TEST_EMP;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

-- 결과저장용 임시 테이블 생성
	DROP TEMPORARY TABLE IF EXISTS TEMP_EMP;
    CREATE TEMPORARY TABLE TEMP_EMP(
		ENAME 	VARCHAR(20),
        SAL 	DECIMAL(10,2)
	);
    
	OPEN cur1;

	read_loop: LOOP
		FETCH cur1 INTO RES_ENAME, RES_SAL;
    
		IF done THEN
		  LEAVE read_loop;
		END IF;
		INSERT INTO TEMP_EMP(ENAME, SAL) VALUES(RES_ENAME, RES_SAL);
	END LOOP;
	CLOSE cur1;
    -- 전체 출력
    SELECT ENAME, SAL FROM TEMP_EMP;
    
END