SHOW VARIABLES  LIKE  'NO_AUTO_VALUE_ON_ZERO'; # 컬럼에 AUTO_INCREMENT 0값 저장 안함  

-- Q1. 파일을 생성해서 자동증가 값을 확인 해보자.
DROP TABLE MY_FILE;

CREATE TABLE MY_FILE(
    ID INT AUTO_INCREMENT PRIMARY KEY,  -- 고유값 + NOT NULL
    NAME VARCHAR(20)
);

INSERT INTO MY_FILE VALUES(NULL, '1');
INSERT INTO MY_FILE VALUES('A', '1');

INSERT INTO MY_FILE(NAME) VALUES('3');

SELECT *
FROM MY_FILE;

-- Q2. 파일을 생성해서 테이블에 저장해보자.

CREATE TABLE MY_FILE(
    ID INT AUTO_INCREMENT  PRIMARY KEY,   # NO_AUTO_VALUE_ON_ZERO, PRIMARY KEY(U + NOT NULL)  
    FILE_CONTENT  LONGTEXT -- LONGTEXT : 큰 글자를 입력할 수 있는 문자형타입 이것보단 B
);

DESC MY_FILE;
DESC EMP;

INSERT INTO MY_FILE(FILE_CONTENT)  
  VALUES(LOAD_FILE('C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\A.TXT'));  
         
SELECT ID, FILE_CONTENT  
FROM MY_FILE;

DELETE FROM MY_FILE; -- 테이블의 내용을 삭제. 구조는 그대로
DESC MY_FILE;


-- Q3. 이미지 파일을 생성해서 테이블에 저장해보자.
DROP TABLE MY_IMAGE;

CREATE TABLE MY_IMAGE(
  ID INT AUTO_INCREMENT  PRIMARY KEY, 
  IMG_CONTENT  BLOB
); 

DESC MY_IMAGE;
INSERT INTO MY_IMAGE(IMG_CONTENT)  
  VALUES(LOAD_FILE('C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\A.TXT')),    -- VALUS안에 ,로 나열해서 행으로 삽입
        (LOAD_FILE('C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\GGOMI.PNG'));  

INSERT INTO MY_IMAGE(IMG_CONTENT)  
  VALUES(LOAD_FILE('C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\A.TXT')),  
                   (LOAD_FILE('C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\GGOMI.PNG'));

SELECT IMG_CONTENT
FROM MY_IMAGE;
COMMIT;  -- RUD 명령이 저장됨

DELETE FROM  MY_IMAGE;
COMMIT;