USE world;
-- 각 테이블의 내용을 확인 하자.
SELECT * FROM CITY;
SELECT * FROM COUNTRY;
SELECT * FROM COUNTRYLANGUAGE;

-- Q1. 모든 도시(city)의 이름과 해당 국가(country)의 이름을 출력하되, 각각 City와 Country라는 별칭으로 표시하자.
-- ANSI
SELECT CITY.NAME AS CITY, COUNTRY.NAME AS COUNTRY
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE;

-- MYSQL
SELECT CITY.NAME AS CITY, COUNTRY.NAME AS COUNTRY
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE;

-- Q2. 인구 수가 100만 이상인 도시 이름, 인구, 해당 국가 이름을 출력하되, 도시의 인구가 기준이다.
-- ANSI
SELECT CITY.NAME, CITY.POPULATION, COUNTRY.NAME
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE CITY.POPULATION >= 1000000;

-- MYSQL
SELECT CITY.NAME, CITY.POPULATION, COUNTRY.NAME
FROM CITY, COUNTRY 
WHERE CITY.COUNTRYCODE = COUNTRY.CODE
AND CITY.POPULATION >= 1000000;

-- Q3. 도시 이름, 국가 코드, 해당 도시가 속한 국가에서 사용되는 언어를 출력하자.
-- ANSI
SELECT CITY.NAME, CITY.COUNTRYCODE, LANGUAGE
FROM CITY
JOIN COUNTRYLANGUAGE ON CITY.COUNTRYCODE = COUNTRYLANGUAGE.COUNTRYCODE;

-- MYSQL
SELECT CITY.NAME, CITY.COUNTRYCODE, LANGUAGE
FROM CITY, COUNTRYLANGUAGE
WHERE CITY.COUNTRYCODE = COUNTRYLANGUAGE.COUNTRYCODE;

-- Q4. 공용 언어(IsOfficial='T')만 골라 언어 이름과 해당 국가 이름을 출력하자.
-- ANSI
SELECT LANGUAGE, COUNTRY.NAME
FROM COUNTRYLANGUAGE
JOIN COUNTRY ON COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE
WHERE ISOFFICIAL = 'T';

-- MYSQL
SELECT LANGUAGE, COUNTRY.NAME
FROM COUNTRY, COUNTRYLANGUAGE
WHERE COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE
AND ISOFFICIAL = 'T';

-- Q5. 아시아 대륙에 속한 국가에 있는 도시의 이름과 인구를 출력하자.
-- ANSI
SELECT CITY.NAME, CITY.POPULATION
FROM CITY JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE CONTINENT = 'ASIA';

-- MYSQL
SELECT CITY.NAME, CITY.POPULATION
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE
AND CONTINENT = 'ASIA';

-- Q6. 기대 수명(LifeExpectancy)이 80 이상인 국가의 이름과 대륙을 출력하자.
-- ANSI
SELECT COUNTRY.NAME, CONTINENT
FROM COUNTRY
WHERE LIFEEXPECTANCY >= 80;

-- MYSQL

-- Q7. 공용어가 영어인 국가의 이름만 출력하자.
-- ANSI
SELECT COUNTRY.NAME
FROM COUNTRY
JOIN COUNTRYLANGUAGE ON COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE
WHERE LANGUAGE = 'ENGLISH' AND ISOFFICIAL = 'T';

-- MYSQL
SELECT COUNTRY.NAME
FROM COUNTRY, COUNTRYLANGUAGE
WHERE COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE
AND LANGUAGE = 'ENGLISH' AND ISOFFICIAL = 'T';

-- Q8. 모든 국가의 이름과 수도 도시의 이름을 각각 Country, Capital로 별칭을 주어 출력하자.
-- ANSI
SELECT COUNTRY.NAME AS COUNTRY, CITY.NAME AS CAPITAL
FROM COUNTRY JOIN CITY ON (COUNTRY.CODE = CITY.COUNTRYCODE)
WHERE COUNTRY.CAPITAL = CITY.ID;

-- MYSQL
SELECT COUNTRY.NAME AS COUNTRY, CITY.NAME AS CAPITAL
FROM COUNTRY, CITY 
WHERE COUNTRY.CODE = CITY.COUNTRYCODE 
AND COUNTRY.CAPITAL = CITY.ID;

-- Q9. 도시 이름, 도시 인구, 해당 국가의 지역(region)을 출력하자.
-- ANSI
SELECT CITY.NAME, CITY.POPULATION, COUNTRY.REGION
FROM CITY
JOIN COUNTRY ON (CITY.COUNTRYCODE = COUNTRY.CODE);

-- MYSQL
SELECT CITY.NAME, CITY.POPULATION, COUNTRY.REGION
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE;

-- Q10. 인구가 500만 이상인 국가에서 사용되는 언어를 해당 국가 이름과 함께 출력하자.
-- ANSI
SELECT LANGUAGE, COUNTRY.NAME
FROM COUNTRYLANGUAGE
JOIN COUNTRY ON (COUNTRYLANGUAGE.COUNTRYCODE = COUNTRY.CODE)
WHERE COUNTRY.POPULATION >= 5000000;

-- MYSQL
SELECT LANGUAGE, COUNTRY.NAME
FROM COUNTRYLANGUAGE, COUNTRY
WHERE COUNTRYLANGUAGE.COUNTRYCODE = COUNTRY.CODE
AND COUNTRY.POPULATION >= 5000000;

-- Q11. 도시 이름과 해당 국가의 정부 형태(GovernmentForm)를 출력하자.
-- ANSI
SELECT CITY.NAME, GOVERNMENTFORM
FROM CITY
JOIN COUNTRY ON (CITY.COUNTRYCODE = COUNTRY.CODE);

-- MYSQL
SELECT CITY.NAME, GOVERNMENTFORM
FROM CITY, COUNTRY 
WHERE CITY.COUNTRYCODE = COUNTRY.CODE;

-- Q12. 공용어가 영어인 국가에 속한 도시 이름을 중복 없이 출력하자.
-- ANSI
SELECT DISTINCT CITY.NAME
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
JOIN COUNTRYLANGUAGE ON COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE
WHERE LANGUAGE = 'ENGLISH' AND ISOFFICIAL = 'T';

-- MYSQL
SELECT DISTINCT CITY.NAME
FROM CITY, COUNTRY, COUNTRYLANGUAGE
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE
AND (LANGUAGE = 'ENGLISH' AND ISOFFICIAL = 'T');

-- Q13. 국가 이름과 그 국가에서 사용되는 언어 이름을 출력하자.
-- ANSI
SELECT COUNTRY.NAME, LANGUAGE
FROM COUNTRY
JOIN COUNTRYLANGUAGE;

-- MYSQL
SELECT COUNTRY.NAME, LANGUAGE
FROM COUNTRY, COUNTRYLANGUAGE;

-- Q14. 모든 국가의 이름과 수도 도시의 인구를 출력하자.
-- ANSI
SELECT COUNTRY.NAME, CITY.POPULATION
FROM COUNTRY
JOIN CITY ON COUNTRY.CODE = CITY.COUNTRYCODE
WHERE CITY.ID = COUNTRY.CAPITAL;

-- MYSQL
SELECT COUNTRY.NAME, CITY.POPULATION
FROM COUNTRY, CITY 
WHERE COUNTRY.CODE = CITY.COUNTRYCODE
AND CITY.ID = COUNTRY.CAPITAL;

-- Q15. 도시 이름과 해당 국가의 독립 연도(IndepYear)를 출력하자.
-- ANSI
SELECT CITY.NAME, COUNTRY.INDEPYEAR
FROM CITY
JOIN COUNTRY ON (CITY.COUNTRYCODE = COUNTRY.CODE);
-- WHERE CITY.NAME = 'SEOUL';

-- MYSQL
SELECT CITY.NAME, COUNTRY.INDEPYEAR
FROM CITY, COUNTRY 
WHERE (CITY.COUNTRYCODE = COUNTRY.CODE);

-- Q16. 사용 언어 수가 5개 이상인 국가의 이름을 출력하자. 에서  
--  같은 나라에 속한 모든 언어를 하나의 그룹으로 같은 나라별 언어 수를 COUNT로 조건문으로구현  합니다,
-- ANSI
SELECT COUNTRY.NAME, COUNT(*) AS LANGUAGE_COUNT
FROM COUNTRY
JOIN COUNTRYLANGUAGE ON (COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE)
GROUP BY COUNTRY.NAME
HAVING COUNT(*) > 5;

-- MYSQL
SELECT COUNTRY.NAME, COUNT(*) AS LANGUAGE_COUNT
FROM COUNTRY, COUNTRYLANGUAGE 
WHERE (COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE)
GROUP BY COUNTRY.NAME
HAVING COUNT(*) > 5;

-- Q17. 도시 이름과 그 도시가 속한 국가의 국토 면적(SurfaceArea)을 출력하자.
-- ANSI
SELECT CITY.NAME, SURFACEAREA AS COUNTRY_AREA
FROM CITY
JOIN COUNTRY ON (CITY.COUNTRYCODE = COUNTRY.CODE);

-- MYSQL
SELECT CITY.NAME, SURFACEAREA AS COUNTRY_AREA
FROM CITY, COUNTRY
WHERE (CITY.COUNTRYCODE = COUNTRY.CODE);

-- Q18. 아프리카 대륙에 속한 국가의 이름과 수도 도시 이름을 출력하자.
-- ANSI
SELECT COUNTRY.NAME, CITY.NAME
FROM COUNTRY
JOIN CITY ON (COUNTRY.CODE = CITY.COUNTRYCODE)
WHERE CONTINENT = 'AFRICA' AND COUNTRY.CAPITAL = CITY.ID;

-- MYSQL
SELECT COUNTRY.NAME, CITY.NAME
FROM COUNTRY, CITY
WHERE (COUNTRY.CODE = CITY.COUNTRYCODE)
AND (CONTINENT = 'AFRICA' AND COUNTRY.CAPITAL = CITY.ID);

-- Q19. 전 세계에서 인구가 가장 많은 도시의 이름과 그 도시가 속한 국가 이름을 출력하자.
-- ANSI
SELECT CITY.NAME, COUNTRY.NAME
FROM CITY
JOIN COUNTRY ON (CITY.COUNTRYCODE = COUNTRY.CODE)
ORDER BY CITY.POPULATION DESC
LIMIT 1;

-- MYSQL
SELECT CITY.NAME, COUNTRY.NAME, CITY.POPULATION
FROM CITY ,COUNTRY 
WHERE (CITY.COUNTRYCODE = COUNTRY.CODE)
ORDER BY CITY.POPULATION DESC
LIMIT 1;

-- Q20. 도시 인구의 평균이 100만 이상인 국가의 이름을 출력하자.
-- ANSI
SELECT COUNTRY.NAME, AVG(CITY.POPULATION)
FROM COUNTRY
JOIN CITY ON (CITY.COUNTRYCODE = COUNTRY.CODE)
GROUP BY COUNTRY.NAME
HAVING AVG(CITY.POPULATION) > 1000000;

-- MYSQL
SELECT COUNTRY.NAME, AVG(CITY.POPULATION)
FROM COUNTRY, CITY
WHERE (CITY.COUNTRYCODE = COUNTRY.CODE)
GROUP BY COUNTRY.NAME
HAVING AVG(CITY.POPULATION) > 1000000;